### ISSUE TITLE
仿真环境

### ISSUE THREAD

**Issue by Ningchj** [jw007123/Model-Predictive-Control-on-Differentiable-Manifolds#1]
请问您做了该方法的车辆控制仿真吗？使用的什么仿真软件搭建的环境呢？chrono吗？

**Comment by jw007123** [comment]
I had to translate your comment, sorry. 

This code hasn't yet been deployed to a live platform for testing, but will be in the next couple of months (fingers crossed).

Cheers

**Comment by Ningchj** [comment]
Okay, haha, thank you for reproducing and open-sourcing the code for the paper. Looking forward to your success on a live platform for testing in the future
